version: '3'
services:
  node:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=Development

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:


# 
#  - DATABASE_CONNECTIONSTRING=mongodb://mongo:27017/notes  
# version: '3'
# services:
#   node:
#     restart: always
#     build: .
#     ports:
#       - 80:5000
#     volumes:
#       - ./:/code
#   mongo:
#     image: mongo
#     ports:
#       - 27017:27017
#     volumes:
#       - mongodb:/data/db
# volumes:
#  mongodb:


# version: "3.8"

# services:
#   mongodb:
#     image: mongo:5.0.2
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
#       - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
#     ports:
#       - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
#     volumes:
#       - db:/data/db
#   node:
#     depends_on:
#       - mongodb
#     build: .
#     restart: always
#     ports:
#       - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
#     environment:
#       - DB_HOST=mongodb
#       - DB_USER=$MONGODB_USER
#       - DB_PASSWORD=$MONGODB_PASSWORD
#       - DB_NAME=$MONGODB_DATABASE
#       - DB_PORT=$MONGODB_DOCKER_PORT
#     stdin_open: true
#     tty: true

# volumes:
#   db: